# Generated by Django 3.0.3 on 2020-03-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonCompany',
            fields=[
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('total_emissions', models.IntegerField(blank=True, null=True)),
                ('reporting_period', models.DateField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Carbon_Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarbonIndustry',
            fields=[
                ('year', models.IntegerField()),
                ('industry', models.CharField(max_length=255)),
                ('intensity', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('industry_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Carbon_Industry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('company_address', models.CharField(max_length=255)),
                ('company_no', models.CharField(blank=True, max_length=30, null=True)),
                ('joining_date', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('contact_no', models.CharField(blank=True, max_length=30, null=True)),
                ('no_of_employees', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WasteCompany',
            fields=[
                ('customer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Waste_Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WasteIndustry',
            fields=[
                ('year', models.IntegerField()),
                ('industry', models.CharField(max_length=100)),
                ('total_amount', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=25, null=True)),
                ('industry_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Waste_Industry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterCompany',
            fields=[
                ('customer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('reporting_period', models.CharField(max_length=255)),
                ('bill_amount', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Water_Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterIndustry',
            fields=[
                ('year', models.IntegerField()),
                ('industry', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Water_Industry',
                'managed': False,
            },
        ),
    ]
