# Generated by Django 3.0.3 on 2020-03-27 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0002_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userdata',
            name='company_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='company_id',
            field=models.CharField(default='a1', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='company_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='contact_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='no_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
