# Generated by Django 3.0.3 on 2020-03-29 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nile_App', '0003_auto_20200327_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('company_address', models.CharField(max_length=255, null=True)),
                ('joining_date', models.DateField()),
                ('contact_no', models.CharField(blank=True, max_length=30, null=True)),
                ('no_of_employees', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(default='Unassigned', max_length=255, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
