# Generated by Django 3.0.3 on 2020-04-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0020_auto_20200407_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
    ]
