# Generated by Django 3.0.3 on 2020-04-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0022_auto_20200407_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carboncompany',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
    ]
