# Generated by Django 3.0.3 on 2020-04-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0023_auto_20200407_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbonindustry',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='wastecompany',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='wasteindustry',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='watercompany',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='waterindustry',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
    ]
