# Generated by Django 3.0.3 on 2020-04-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0025_auto_20200407_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=30, editable=False, null=True),
        ),
    ]
