# Generated by Django 3.0.3 on 2020-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0026_auto_20200407_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watercompany',
            old_name='bill_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='watercompany',
            old_name='customer_id',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='watercompany',
            old_name='customer_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='watercompany',
            name='reporting_period',
        ),
        migrations.AddField(
            model_name='watercompany',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=17, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='watercompany',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=15, editable=False, null=True),
        ),
    ]
