# Generated by Django 3.0.3 on 2020-04-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0027_auto_20200407_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastecompany',
            old_name='customer_id',
            new_name='company_id',
        ),
        migrations.AddField(
            model_name='wastecompany',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastecompany',
            name='company_name',
            field=models.CharField(default=0.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastecompany',
            name='industry',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastecompany',
            name='type',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastecompany',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=18, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='watercompany',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
        migrations.AlterField(
            model_name='watercompany',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=12, editable=False, null=True),
        ),
    ]
