# Generated by Django 3.0.3 on 2020-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0028_auto_20200407_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=28, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='wastecompany',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='wastecompany',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastecompany',
            name='industry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wastecompany',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wastecompany',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='watercompany',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=15, editable=False, null=True),
        ),
    ]
