# Generated by Django 3.0.3 on 2020-04-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0029_auto_20200407_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='carboncompany',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=26, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='watercompany',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
        migrations.AlterField(
            model_name='watercompany',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=10, editable=False, null=True),
        ),
    ]
