# Generated by Django 3.0.3 on 2020-04-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0030_auto_20200407_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carboncompany',
            old_name='company_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wastecompany',
            old_name='company_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='watercompany',
            old_name='company_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=12, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='watercompany',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
        migrations.AlterField(
            model_name='watercompany',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=16, editable=False, null=True),
        ),
    ]
