# Generated by Django 3.0.3 on 2020-04-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0031_auto_20200407_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watercompany',
            name='amount',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=24, editable=False, null=True),
        ),
    ]
