# Generated by Django 3.0.3 on 2020-04-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0032_auto_20200407_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=15, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='watercompany',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=27, editable=False, null=True),
        ),
    ]
