# Generated by Django 3.0.3 on 2020-04-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0037_auto_20200408_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='watercompany',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=13, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='watercompany',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=12, editable=False, null=True),
        ),
    ]
