# Generated by Django 3.0.3 on 2020-04-25 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0039_auto_20200409_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteindustry',
            name='industry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watercompany',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=11, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='waterindustry',
            name='industry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
