# Generated by Django 3.0.3 on 2020-04-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile_App', '0040_auto_20200425_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterindustry',
            name='provider',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=25, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='watercompany',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=21, editable=False, null=True),
        ),
    ]
